### ISSUE TITLE
Regarding DNS IP

### ISSUE THREAD

**Issue by devnv13** [prasenforu/openshift-origin-aws#1]
Hi,

I've godaddy domain name. Want to know where we can found DNS Server IP as you mentioned in "Preparation of custom DNS Environment in AWS" at point 6 (Give DNS server IP in Domain name servers). Rest everything is clear. Please do the needful.

Thanks,
Vasu

**Comment by prasenforu** [comment]
https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html

Follow above URL and go to section 

"Creating DHCP options set"
